name: tubes_ppb_sem5
description: "Project Flutter untuk tubes"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Favorite/cah_kangkung.png
    - assets/images/Favorite/mie_nyemek.png
    - assets/images/Favorite/nasi_goreng.png
    - assets/images/Favorite/tahu_cabe_garam.png
    - assets/images/Favorite/telur_orak_arik.png
    - assets/images/Favorite/telur_sosis.png
    - assets/images/Favorite/tumis_jamur.png
    - assets/images/Home/cah_kangkung.png
    - assets/images/Home/mie_nyemek.png
    - assets/images/Home/nasi_goreng_di.png
    - assets/images/Home/tahu_cabe_garam.png
    - assets/images/Home/telur_orak_arik.png
    - assets/images/Recent/
    - assets/images/Recommend/
    - assets/images/See_All/
    - assets/images/Sosmed/
    - assets/images/Uploud/
    - assets/images/Video/
    - assets/images/google_icon.png
    - assets/images/facebook_icon.jpg
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700
